#!/bin/bash

# Disk WWN list
DISKS="0x5000cca7dcd6f399 0x5000cca7dcd6f2c0 0x50024e9204a90b4a \
    0x5000cca7dcd7123f 0x50024e9204a90d59 0x50024e9204a90d45"
ID=0
for DISK in $DISKS
do
    printf "parted -a optimal /dev/disk/by-id/wwn-${DISK}\n"
    printf "mklabel gpt\nmkpart primary 1 -1\nname 1 pool${ID}\n\n"
    ID=$(($ID + 1))
done

# Properties for the pool
# ashift=12                     - Support 4KiB sectors
# autoexpand=on                 - Allow automatic disk expansion
# feature@lz4_compress=enabled  - Enable support for lz4 compression
for DISK in $DISKS
do
    echo "/dev/disk/by-id/wwn-${DISK}-part1"
done

zpool create -o ashift=12 -o autoexpand=on -o feature@lz4_compress=enabled \
    fpool raidz1 \
    /dev/disk/by-id/wwn-0x5000cca7dcd6f399-part1 \
    /dev/disk/by-id/wwn-0x5000cca7dcd6f2c0-part1 \
    /dev/disk/by-id/wwn-0x50024e9204a90b4a-part1 \
    /dev/disk/by-id/wwn-0x5000cca7dcd7123f-part1 \
    /dev/disk/by-id/wwn-0x50024e9204a90d59-part1 \
    /dev/disk/by-id/wwn-0x50024e9204a90d45-part1

# Clone
zfs snap -r dpool@migrate
zfs send -R dpool@migrate | zfs recv -F fpool

# Origininal 
zpool create -o ashift=12 -o autoexpand=on -o feature@lz4_compress=enabled \
    dpool raidz1 /dev/disk/by-id/ata-WDC_WD1001FALS-00E3A0_WD-WCATR0086402-part1 \
    /dev/disk/by-id/scsi-3600050e0a5e0d600b66c0000b77b0000-part1 \
    /dev/disk/by-id/scsi-3600050e0a5e0d600f8ec0000a7bb0000-part1 \
    /dev/disk/by-id/scsi-3600050e0a5e0db00739a0000d6930000-part1 \
    /dev/disk/by-id/scsi-3600050e0a5e0db00a318000042e30000-part1 \
    log mirror /dev/disk/by-id/wwn-0x5001b44bd5ba5a9d-part1 \
    /dev/disk/by-id/wwn-0x5001b44bd5ba5baf-part1 \
    cache /dev/disk/by-id/wwn-0x5001b44bd5ba5a9d-part2 \
    /dev/disk/by-id/wwn-0x5001b44bd5ba5baf-part2

# Base file system
zfs create -o mountpoint=none dpool/DATA

# create file systems
zfs create -o mountpoint=/dpool/software -o compression=lz4 dpool/DATA/software
zfs create -o mountpoint=/dpool/media -o compression=lz4 dpool/DATA/media
zfs create -o mountpoint=/dpool/media/encoded -o compression=lz4 dpool/DATA/media/encoded
zfs create -o mountpoint=/dpool/media/transcode -o compression=lz4 dpool/DATA/media/transcode
zfs create -o mountpoint=none -o compression=lz4 dpool/HOME
zfs create -o mountpoint=/home/pdemonaco/documents -o compression=lz4 dpool/HOME/documents
zfs create -o mountpoint=none -o compression=lz4 dpool/DEV
zfs create -o mountpoint=/var/git -o compression=lz4 dpool/DEV/git
zfs create -o mountpoint=/home/victoria -o compression=lz4 dpool/HOME/victoria

